{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno-authz-server.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "kyverno-authz-server.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "kyverno-authz-server.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kyverno-authz-server.service-account.name" . }}
{{- end -}}
