{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno-authz-server-control-plane.service-account.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "kyverno-authz-server-control-plane.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
