{{- range $key, $value := .Values.authzServer }}
{{- $name := printf "%s-%s" (include "kyverno-authz-server.name" $) $key }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
---
{{- with $value }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno-authz-server.labels" $ | nindent 4 }}
  {{- with .deployment.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .deployment.replicas }}
  replicas: {{ . }}
  {{- end }}
  revisionHistoryLimit: {{ .deployment.revisionHistoryLimit }}
  {{- with .deployment.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kyverno-authz-server.labels.selector" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kyverno-authz-server.labels" $ | nindent 8 }}
        {{- with .pod.labels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .pod.annotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      {{- with .pod.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .pod.securityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .pod.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .pod.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .pod.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .pod.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with .pod.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      affinity:
        {{- with .pod.antiAffinity }}
        podAntiAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .pod.affinity }}
        podAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .pod.nodeAffinity }}
        nodeAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ template "kyverno-authz-server.service-account.name" $ }}
      containers:
        {{- with .container }}
        - name: server
          image: {{ include "kyverno-authz-server.image" (mustMerge .image (dict "tag" (default $.Chart.Version $.Chart.AppVersion))) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .startupProbe }}
          startupProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .ports }}
          ports:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- range $value.config.externalPolicySources }}
            - {{ printf "--external-policy-source=%s" (tpl (toYaml .) $) }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}
