{{- $name := (include "kyverno-authz-server.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
{{- $component := "authz-server" }}
{{- $value := .Values.authzServer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
  {{- with $value.service.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ $value.service.type }}
  ports:
  {{- tpl (toYaml $value.service.ports) $ | nindent 2 }}
  selector:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
