{{- if .Values.sidecarInjector.enabled -}}
{{- $ca := genCA (printf "*.%s.svc" (include "kyverno.lib.namespace" .)) 1024 -}}
{{- $svcName := (printf "%s.%s.svc" (include "sidecar-injector.name" .) (include "kyverno.lib.namespace" .)) -}}
{{- $tls := genSignedCert $svcName nil (list $svcName) 1024 $ca -}}
{{- if .Values.sidecarInjector.certificates.selfSigned -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sidecar-injector.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $tls.Key | b64enc }}
  tls.crt: {{ $tls.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "sidecar-injector.name" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
  {{- with .Values.sidecarInjector.webhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: kyverno-envoy-sidecar.kyverno-envoy-sidecar-injector.svc
    clientConfig:
      service:
        name: {{ template "sidecar-injector.name" . }}
        namespace: {{ template "kyverno.lib.namespace" . }}
        path: "/mutate"
      caBundle: {{ $ca.Cert | b64enc }}
    failurePolicy: {{ .Values.sidecarInjector.webhook.failurePolicy }}
    sideEffects: None
    admissionReviewVersions: [ v1 ]
    rules:
      - apiGroups: [ '' ]
        apiVersions: [ v1 ]
        resources: [ pods ]
        operations: [ CREATE ]
        scope: '*'
    {{- with .Values.sidecarInjector.webhook.objectSelector }}
    objectSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- with .Values.sidecarInjector.webhook.namespaceSelector }}
    namespaceSelector:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
{{- end -}}
