{{- if .Values.sidecarInjector.enabled -}}
{{- $ca := genCA (printf "*.%s.svc" (include "kyverno.namespace" .)) 1024 -}}
{{- $svcName := (printf "%s.%s.svc" (include "kyverno.sidecar-injector.name" .) (include "kyverno.namespace" .)) -}}
{{- $tls := genSignedCert $svcName nil (list $svcName) 1024 $ca -}}
{{- if .Values.sidecarInjector.certificates.selfSigned -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kyverno.sidecar-injector.name" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.sidecar-injector.labels" . | nindent 4 }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $tls.Key | b64enc }}
  tls.crt: {{ $tls.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "kyverno.sidecar-injector.name" . }}
  labels:
    {{- include "kyverno.sidecar-injector.labels" . | nindent 4 }}
webhooks:
  - name: kyverno-envoy-sidecar.kyverno-envoy-sidecar-injector.svc
    clientConfig:
      service:
        name: {{ template "kyverno.sidecar-injector.name" . }}
        namespace: {{ template "kyverno.namespace" . }}
        path: "/mutate"
      caBundle: {{ $ca.Cert | b64enc }}
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
    - v1
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        resources:
          - pods
        operations:
          - CREATE
        scope: '*'  
    objectSelector:
      matchExpressions:
        - key: kyverno-envoy-sidecar/injection
          operator: In
          values:
          - enabled
{{- end -}}
