apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-envoy-sidecar
  namespace: sidecar-injector
data:
  sidecars.yaml: |
    - name: kyverno-envoy-sidecar
      containers:
      - image: sanskardevops/plugin:0.0.25
        imagePullPolicy: IfNotPresent
        name: ext-authz
        ports:
        - containerPort: 8000
        - containerPort: 9000
        args:
        - "serve"
        - "--policy=/policies/policy.yaml"
        volumeMounts:
        - name: policy-files
          mountPath: /policies
      volumes:
      - name: policy-files
        configMap:
          name: policy-files
      