INHERIT: ./mkdocs.base.yaml

nav:
- Home: index.md
- Quick start:
  - quick-start/index.md
  - quick-start/authz-server.md
  - quick-start/sidecar-injector.md
  - quick-start/next-steps.md
  - Install:
    - install/crds.md
    - install/certificates.md
- Policies:
  - policies/index.md
  - policies/failure-policy.md
  - policies/match-conditions.md
  - policies/variables.md
  - policies/authorization-rules.md
- Reference:
  - reference/index.md
  - reference/json-schemas.md
  - APIs:
    - policies.kyverno.io/v1alpha1: reference/apis/policies.kyverno.io.v1alpha1.md
    - envoy.kyverno.io/v1alpha1: reference/apis/envoy.kyverno.io.v1alpha1.md
  - CEL extensions:
    - cel-extensions/index.md
    - cel-extensions/envoy.md
    - cel-extensions/jwt.md
- Tutorials:
  - tutorials/index.md
  - tutorials/istio/index.md
  - tutorials/envoy-gateway/index.md
  - tutorials/kgateway/index.md
- Community:
  - community/index.md
  - Contributing: community/contribute.md
  - Reporting a bug: community/reporting-a-bug.md
  - Reporting a docs issue: community/reporting-a-docs-issue.md
  - Requesting a change: community/requesting-a-change.md
  - Making a pull request: community/making-a-pull-request.md
# - Performance:
#   - performance/index.md
