INHERIT: ./mkdocs.base.yaml

nav:
- Home: index.md
- Getting Started:
  - quick-start/index.md
  - quick-start/local-install.md
  - quick-start/completion.md
  - quick-start/kube-install.md
  - Envoy: quick-start/envoy.md
  - HTTP: quick-start/http.md
  - Sidecar Injector: quick-start/sidecar-injector.md
  - Next Steps: quick-start/next-steps.md
  - Install:
    - install/crds.md
    - install/certificates.md
    - install/external-policy-source.md
- Policies:
  - policies/index.md
  - Envoy Policy Breakdown: policies/envoy-policy-breakdown.md
  - HTTP Policy Breakdown: policies/http-policy-breakdown.md
  - CEL extensions:
    - cel-extensions/index.md
    - cel-extensions/envoy.md
    - cel-extensions/json.md
    - cel-extensions/jwk.md
    - cel-extensions/jwt.md
    - cel-extensions/http.md
- Tutorials:
  - tutorials/index.md
  - tutorials/istio/index.md
  - tutorials/envoy-gateway/index.md
  - tutorials/kgateway/index.md
  - tutorials/ingress-nginx/index.md
- Reference:
  - reference/index.md
  - reference/json-schemas.md
  - APIs:
    - policies.kyverno.io/v1alpha1: reference/apis/policies.kyverno.io.v1alpha1.md
    - authz.kyverno.io/v1alpha1: reference/apis/authz.kyverno.io.v1alpha1.md
  - Command Line:
    - reference/commands/kyverno-envoy-plugin.md
    - reference/commands/kyverno-envoy-plugin_completion.md
    - reference/commands/kyverno-envoy-plugin_completion_bash.md
    - reference/commands/kyverno-envoy-plugin_completion_fish.md
    - reference/commands/kyverno-envoy-plugin_completion_powershell.md
    - reference/commands/kyverno-envoy-plugin_completion_zsh.md
    - reference/commands/kyverno-envoy-plugin_run.md
    - reference/commands/kyverno-envoy-plugin_serve.md
    - reference/commands/kyverno-envoy-plugin_serve_control-plane.md
    - reference/commands/kyverno-envoy-plugin_serve_envoy.md
    - reference/commands/kyverno-envoy-plugin_serve_envoy_authz-server.md
    - reference/commands/kyverno-envoy-plugin_serve_envoy_validation-webhook.md
    - reference/commands/kyverno-envoy-plugin_serve_http.md
    - reference/commands/kyverno-envoy-plugin_serve_http_authz-server.md
    - reference/commands/kyverno-envoy-plugin_serve_http_validation-webhook.md
    - reference/commands/kyverno-envoy-plugin_serve_sidecar-injector.md
    - reference/commands/kyverno-envoy-plugin_version.md
- Community:
  - community/index.md
  - Contributing: community/contribute.md
  - Reporting a bug: community/reporting-a-bug.md
  - Reporting a docs issue: community/reporting-a-docs-issue.md
  - Requesting a change: community/requesting-a-change.md
  - Making a pull request: community/making-a-pull-request.md
# - Performance:
#   - performance/index.md
