{{- $name := (include "validation-webhook.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
{{- $component := "validation-webhook" }}
{{- $value := .Values.validatingWebhookConfiguration }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
  {{- with $value.deployment.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with $value.deployment.replicas }}
  replicas: {{ . }}
  {{- end }}
  revisionHistoryLimit: {{ $value.deployment.revisionHistoryLimit }}
  {{- with $value.deployment.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kyverno.lib.labels.merge" (list
        (include "kyverno.lib.labels.common.selector" $)
        (include "kyverno.lib.labels.component" $component)
      ) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kyverno.lib.labels.merge" (list
          (include "kyverno.lib.labels.common" $)
          (include "kyverno.lib.labels.common.selector" $)
          (include "kyverno.lib.labels.component" $component)
        ) | nindent 8 }}
        {{- with $value.pod.labels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with $value.pod.annotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      {{- with $value.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $value.pod.securityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $value.pod.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $value.pod.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $value.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $value.pod.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with $value.pod.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with $value.pod.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      affinity:
        {{- with $value.pod.antiAffinity }}
        podAntiAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with $value.pod.affinity }}
        podAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with $value.pod.nodeAffinity }}
        nodeAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ template "kyverno-authz-server.service-account.name" $ }}
      volumes:
        - name: certs
          secret:
            secretName: {{ template "validation-webhook.name" $ }}
      containers:
        {{- with $value.container }}
        - name: server
          image: {{ include "kyverno-authz-server.image" (mustMerge .image (dict "tag" (default $.Chart.Version $.Chart.AppVersion))) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .startupProbe }}
          startupProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .ports }}
          ports:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          args:
          - serve
          - '{{ $.Values.config.type }}'
          - validation-webhook
          - --probes-address=:9080
          - --metrics-address=:9082
          volumeMounts:
            - name: certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
        {{- end }}
