{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "validation-webhook.service-account.name" . }}
  namespace: {{ template "kyverno.lib.namespace" . }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" "validation-webhook")
    ) | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
