{{- range $key, $_ := .Values.validatingWebhookConfiguration.webhooks }}
{{- $name := printf "%s-%s" (include "validation-webhook.name" $) $key }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" (printf "validation-webhook-%s" $key ))
    ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" (printf "validation-webhook-%s" $key ))
    ) | nindent 4 }}
{{- end }}
