{{- $name := (include "validation-webhook.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
{{- $component := "validation-webhook" }}
{{- $value := .Values.validatingWebhookConfiguration }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ $name }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
  {{- if (or $value.certificates.certManager $value.annotations) }}
  annotations:
    {{- with $value.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- if $value.certificates.certManager }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" $namespace $name }}
    {{- end }}
  {{- end }}
webhooks:
- name: {{ printf "%s.%s.svc" $name $namespace }}
  clientConfig:
    service:
      name: {{ $name }}
      namespace: {{ $namespace }}
      port: 9443
      path: /validate-policies-kyverno-io-v1alpha1-validatingpolicy
    {{- if $value.certificates.static }}
    caBundle: {{ index $value.certificates.static.crt | b64enc }}
    {{- end }}
  failurePolicy: {{ $value.failurePolicy }}
  sideEffects: None
  admissionReviewVersions: [ v1 ]
  rules:
  - apiGroups: [policies.kyverno.io]
    apiVersions: [v1alpha1]
    resources: [validatingpolicies]
    operations: [CREATE, UPDATE]
