{{- with .Values.validatingWebhookConfiguration.certificates.certManager -}}
{{- $name := (include "validation-webhook.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" "validation-webhook")
    ) | nindent 4 }}
spec:
  secretName: {{ $name }}
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - {{ printf "%s.%s.svc" $name $namespace }}
  {{- with .issuerRef }}
  issuerRef:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
