{{- with .Values.validatingWebhookConfiguration.certificates.certManager -}}
{{- $name := (include "validation-webhook.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "validation-webhook.labels" $ | nindent 4 }}
spec:
  secretName: {{ $name }}
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - {{ printf "%s-http.%s.svc" $name $namespace }}
    - {{ printf "%s-envoy.%s.svc" $name $namespace }}
  {{- with .issuerRef }}
  issuerRef:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
